name: Ruff

on: [push]

jobs:
  ruff:
    name: Ruff lint check
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install uv
        uses: astral-sh/setup-uv@5a095e7a2014a4212f075830d4f7277575a9d098 # v7.3.1

      - name: Install dependencies
        run: uv sync

      - name: Run ruff check
        run: uv run ruff check .
