name: ty

on: [push]

jobs:
  ty:
    name: ty type check
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install uv
        uses: astral-sh/setup-uv@803947b9bd8e9f986429fa0c5a41c367cd732b41 # v7.2.1

      - name: Install dependencies
        run: uv sync

      - name: Run ty check
        run: uv run ty check src/
