name: ty

on: [push]

jobs:
  ty:
    name: ty type check
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install uv
        uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b # v7.3.0

      - name: Install dependencies
        run: uv sync

      - name: Run ty check
        run: uv run ty check src/
