name: ty

on: [push]

jobs:
  ty:
    name: ty type check
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install uv
        uses: astral-sh/setup-uv@61cb8a9741eeb8a550a1b8544337180c0fc8476b # v7.2.0

      - name: Install dependencies
        run: uv sync

      - name: Run ty check
        run: uv run ty check src/
